[workspace]
resolver = "2"
members = [
    "pq-crypto",
    "pq-tunnel-core",
    "pq-tun",
    "pq-proxy",
    "pq-tunnel-bin",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.85"

[workspace.dependencies]
thiserror = "1"
rand = "0.9"
rand_core = "0.9"
getrandom = "0.3"
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
sha2 = "0.10"
rustls = { version = "0.23", features = ["ring"] }
x25519-dalek = "=3.0.0-rc.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
bytes = "1"
zeroize = "1"
pq-crypto = { path = "pq-crypto" }
